/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dadada",
        "secondary": "#5e5e5e",
        "inverse-surface": "#2f3131",
        "primary-container": "#1b1b1b",
        "on-secondary-fixed": "#1b1c1c",
        "surface": "#f9f9f9",
        "secondary-fixed": "#e4e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#c6c6c6",
        "background": "#f9f9f9",
        "secondary-fixed-dim": "#c7c6c6",
        "on-error": "#ffffff",
        "surface-container": "#eeeeee",
        "on-primary": "#ffffff",
        "outline-variant": "#cfc4c5",
        "secondary-container": "#e1dfdf",
        "tertiary-fixed": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "tertiary": "#000000",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#1b1b1b",
        "primary-fixed": "#e2e2e2",
        "outline": "#7e7576",
        "on-primary-container": "#848484",
        "surface-tint": "#5e5e5e",
        "surface-container-high": "#e8e8e8",
        "on-tertiary-container": "#838484",
        "on-tertiary-fixed-variant": "#454747",
        "primary": "#000000",
        "surface-container-low": "#f3f3f4",
        "on-surface-variant": "#4c4546",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1a1c1c",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "inverse-on-surface": "#f0f1f1",
        "on-tertiary-fixed": "#1a1c1c",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-secondary-container": "#626263",
        "surface-container-highest": "#e2e2e2",
        "on-primary-fixed-variant": "#474747",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9f9",
        "on-secondary-fixed-variant": "#464747",
        "inverse-primary": "#c6c6c6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "48px",
        "section-gap": "160px",
        "stack-md": "24px",
        "gutter": "32px",
        "stack-sm": "8px",
        "margin-edge": "64px",
        "container-max": "1280px"
      },
      fontFamily: {
        "quote": ["Libre Caslon Text", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "headline-lg": ["Libre Caslon Text", "serif"],
        "display-lg-mobile": ["Libre Caslon Text", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Libre Caslon Text", "serif"]
      },
      fontSize: {
        "quote": ["24px", {"lineHeight": "36px"}],
        "body-md": ["16px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["80px", {"lineHeight": "96px", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "headline-lg": ["40px", {"lineHeight": "52px", "fontWeight": "400"}],
        "display-lg-mobile": ["48px", {"lineHeight": "56px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "32px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.15em", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
